remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: nielsvd
description: A brief CV and some past projects
show_downloads: false
google_analytics: false
theme: jekyll-theme-hacker