remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: nielsvd
description: Past projects and a brief CV
show_downloads: false
google_analytics: false
theme: jekyll-theme-hacker